name: "Continuous Deployment – Build and Push"
description: "Builds the container image and pushes into the registry"

inputs:
  build-image:
    description: "Should build the container image"
    required: false
    default: "true"

  build-target-tag:
    description: "Build target layer"
    required: true

  load-image:
    description: "Load image"
    required: false

  push-image:
    description: "Enable built image push into the registry"
    required: false
    default: "true"

  image-name:
    description: "Valid container image name"
    required: true

  image-tag:
    description: "Valid container image tag"
    required: true

  push-image-registry-url:
    description: "Registry URL"
    required: false

runs:
  using: composite
  steps:
    - name: Build and push container image to the registry
      if: ${{ inputs.build-image == 'true' }}
      uses: docker/build-push-action@v6
      with:
        push: ${{ inputs.push-image == 'true' }}
        tags: ${{ inputs.push-image-registry-url }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        target: ${{ inputs.build-target-tag }}
        load: ${{ inputs.load-image == 'true' }}
        # platforms: linux/amd64
        # outputs: type=cacheonly
