name: "Continuous Deployment – K8S with stakater/application helm chart"
description: "Deploy resources to kubernetes cluster"

inputs:
  helm-values:
    description: "yaml helm release values"
    required: true
  deployment:
    description: "k8s deployment"
    required: true
  namespace:
    description: "k8s namespace"
    required: true
  helm-release-name:
    description: "helm application namespace"
    required: true
  helm-release-extra-options:
    description: "helm release extra options"
    required: false
    default: "--values=./.devops/values.common.yml"

runs:
  using: composite
  steps:
    - name: deploy resources to kubernetes cluster
      shell: bash
      env:
        K8S_NAMESPACE: ${{ inputs.namespace }}
        K8S_DEPLOYMENT: ${{ inputs.deployment }}
        HELM_RELEASE_NAME: ${{ inputs.helm-release-name }}
        HELM_RELEASE_VALUES: ${{ inputs.helm-values }}
        HELM_RELEASE_EXTRA_OPTIONS: ${{ inputs.helm-release-extra-options }}
      run: |
        set -xe;

        helm repo add --force-update stakater https://stakater.github.io/stakater-charts;
        helm repo update;
        
        echo "${HELM_RELEASE_VALUES}" | helm upgrade -i ${HELM_RELEASE_NAME} stakater/application \
          --namespace=${K8S_NAMESPACE} \
          ${HELM_RELEASE_EXTRA_OPTIONS} \
          -f - \
        ;

        kubectl rollout restart \
          deployment.apps/${K8S_DEPLOYMENT} \
          --namespace ${K8S_NAMESPACE} \
        ;
